site_title = "MyArxiv"
limit_days = 7
cache_url = "https://GooYmmM.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 150
category = "eess.SP"
title = "Signal Processing"

[[sources]]
limit = 150
category = "eess.SY"
title = "Systems and Control"

[[sources]]
limit = 150
category = "cs.IT"
title = "Information Theory"

[[sources]]
limit = 150
category = "math.IT"
title = "Information Theory"

[[sources]]
limit = 150
category = "math.PR"
title = "Probability"

[[sources]]
limit = 150
category = "math.DG"
title = "Differential Geometry"

[[sources]]
limit = 150
category = "math.GT"
title = "Geometric Topology"

[[sources]]
limit = 150
category = "math.OC"
title = "Optimization and Control"

[[sources]]
limit = 150
category = "cs.GT"
title = "Computer Science and Game Theory"

[[sources]]
limit = 150
category = "cs.HC"
title = "Human-Computer Interaction"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.NE"
title = "Neural and Evolutionary Computing"

[[sources]]
limit = 150
category = "cs.NA"
title = "Numerical Analysis"

[[sources]]
limit = 150
category = "cs.SY"
title = "Systems and Control"

[[sources]]
limit = 150
category = "stat.ME"
title = "Methodology"

[[sources]]
limit = 150
category = "cs.GR"
title = "Graphics"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
